# Setup
title:               Intelligent Storage
tagline:             'Cultivating sensitivity to difficulties'
description:         ''
url:                 https://intelligent-storage.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Intelligent Storage
  url:               https://intelligent-storage.github.io
  email:             IntelligentStorage@proton.me

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
